import json

liberaal = "rgb(0,102,153)"
sociaal = "rgb(255,0,0)"
liberaal_sociaal = "rgb(98,8,121)" 
communist = "rgb(222,41,16)"
katholiek = "rgb(255,153,51)"
vlaams_nationalistisch = "rgb(255,204,102)"
waals_nationalistisch = "rgb(184,41,108)"
duits_nationalistisch = "rgb(251,194,3)"
extreem_rechts = "rgb(255,255,0)"
fascistisch = "rgb(255,255,0)"
groen = "rgb(0,153,102)"
none = "rgb(156,156,156)"

partijkleuren = dict()
partijkleuren['PSC'] = katholiek
partijkleuren["PS"] = sociaal
partijkleuren["PSB"] = sociaal
partijkleuren['PSB(BRUX)'] = sociaal
partijkleuren["SP"] = sociaal
partijkleuren["SP/PS"] = sociaal
partijkleuren["sp.a"] = sociaal
partijkleuren['sp.a-spirit'] = sociaal
partijkleuren['Social'] = sociaal
partijkleuren['Socialistische Partij'] = sociaal
partijkleuren['PSB-BSP'] = sociaal
partijkleuren['parti ouvrier belge-belgische werkliedenpartij'] = sociaal
partijkleuren["BWP/POB"] = sociaal
partijkleuren['PSB-RW'] = sociaal
partijkleuren['BSP'] = sociaal
partijkleuren['BSP RODE LEEUWEN'] = sociaal
partijkleuren['RODE LEEUW'] = sociaal
partijkleuren['BSP/PSB'] = sociaal
partijkleuren['CARTEL'] = liberaal_sociaal
partijkleuren['CARTEL LIB/s'] = liberaal_sociaal
partijkleuren['CARTEL LIB/ soc'] = liberaal_sociaal
partijkleuren['Cartel Lib/Soc'] = liberaal_sociaal
partijkleuren['Cartel Lib/Soc LIB/ soc'] = liberaal_sociaal
partijkleuren["Cartel Lib/Soc LIB/s"] = liberaal_sociaal
partijkleuren['cartel libéral-socialiste'] = liberaal_sociaal
partijkleuren["Open Vld"] = liberaal
partijkleuren['open vld'] = liberaal
partijkleuren["VLD"] = liberaal
partijkleuren["PLP"] = liberaal
partijkleuren['PVV/PLP'] = liberaal
partijkleuren['parti libéral-liberale partij'] = liberaal
partijkleuren['PVV'] = liberaal
partijkleuren["MR"] = liberaal
partijkleuren["PRL"] = liberaal
partijkleuren["PRL-FDF"] = liberaal
partijkleuren["PRL/PFF"] = liberaal
partijkleuren['PRLW'] = liberaal
partijkleuren['PRLW/PRF'] = liberaal
partijkleuren['Liberal/Liberaal'] = liberaal
partijkleuren['Parti Liberale/Liberale '] = liberaal
partijkleuren['Liberale Partij'] = liberaal
partijkleuren["CD&V"] = katholiek
partijkleuren['CD&V; NVA'] = katholiek
partijkleuren['CD&V NVA'] = katholiek
partijkleuren['CD&V/N-VA'] = katholiek
partijkleuren['CVP'] = katholiek
partijkleuren['Cath/Kath'] = katholiek
partijkleuren["CATH +OUVR"] = katholiek
partijkleuren['VDB/CVP'] = katholiek
partijkleuren["CDH"] = katholiek
partijkleuren['Christ. Werklieden/Ouvri'] = katholiek
partijkleuren['Christelijke Werklieden'] = katholiek
partijkleuren['Christene Volkspartij'] = katholiek
partijkleuren['union catholique belge'] = katholiek
partijkleuren["PSC"] = katholiek
partijkleuren['PSC-CSP'] = katholiek
partijkleuren['PSC/CSP'] = katholiek
partijkleuren['PSC/CVP'] = katholiek
partijkleuren['Diss. Kath.'] = katholiek
partijkleuren['Onafhankelijk/Dissidente Katholiek'] = katholiek
partijkleuren["N-VA"] = vlaams_nationalistisch
partijkleuren["Frontpartij"] = vlaams_nationalistisch
partijkleuren['VU'] = vlaams_nationalistisch
partijkleuren['Vl. National.Fl'] = vlaams_nationalistisch
partijkleuren['VU-ID'] = vlaams_nationalistisch
partijkleuren['K.V.V. -'] = vlaams_nationalistisch
partijkleuren['ECOLO'] = groen
partijkleuren['KPB/PCB'] = communist
partijkleuren['PC'] = communist
partijkleuren['Heimattreue Front'] = duits_nationalistisch
partijkleuren['Parti pop. DEupen'] = duits_nationalistisch
partijkleuren['PDB'] = duits_nationalistisch
partijkleuren['Kartel Lib Soc'] = liberaal_sociaal
partijkleuren['FDF'] = waals_nationalistisch
partijkleuren['RW'] = waals_nationalistisch
partijkleuren['RLiège'] = waals_nationalistisch
partijkleuren['Retour à Liège'] = waals_nationalistisch
partijkleuren['FDF-PLDP'] = waals_nationalistisch
partijkleuren['FDF-RW'] = waals_nationalistisch
partijkleuren['Rex'] = fascistisch
partijkleuren['VLAAMS BELANG'] = extreem_rechts
partijkleuren['VLAAMS BLOK'] = extreem_rechts
partijkleuren["None"] = none


json.dump(partijkleuren,open("geodata/Verkiezingen/output/partijkleuren.json","w"))